SET IDENTITY_INSERT Productos ON;

INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (1, 'Xiaomi Redmi Note 13 Pro+ 5G', 'Plan Postpago', 11489.33, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (2, 'POCO X6 Pro', 'Plan Prepago', 10153.33, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (3, 'POCO M6 Pro', 'Plan Postpago', 6946.93, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (4, 'Samsung Galaxy S24 Ultra', 'Plan Postpago', 28029.28, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (5, 'Samsung Galaxy S24+', 'Plan Postpago', 24021.28, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (6, 'Samsung Galaxy S24', 'Plan Postpago', 20013.28, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (7, 'OnePlus 12', 'Plan Prepago', 22976.52, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (8, 'Honor Magic6 Pro', 'Plan Postpago', 26693.28, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (9, 'Nothing Phone 2a', 'Plan Postpago', 7989.28, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (10, 'Xiaomi 14', 'Plan Prepago', 29389.32, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (11, 'realme 12 Pro+', 'Plan Prepago', 9457.00, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (12, 'Xiaomi 14 Ultra', 'Plan Postpago', 32357.65, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (13, 'Motorola Edge 50 Pro', 'Plan Postpago', 13707.36, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (14, 'OPPO Reno11 F 5G', 'Plan Postpago', 7187.68, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (15, 'Samsung Galaxy A55', 'Plan Prepago', 8641.51, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (16, 'Google Pixel 8a', 'Plan Prepago', 11997.28, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (17, 'Huawei Pura 70 Ultra', 'Plan Postpago', 37381.28, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (18, 'Honor 200 Pro', 'Plan Postpago', 21349.28, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (19, 'POCO F6 Pro', 'Plan Postpago', 14161.33, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (20, 'realme GT 6T', 'Plan Postpago', 10153.33, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (21, 'Motorola Edge 50 Ultra', 'Plan Postpago', 24021.54, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (22, 'Vivo V40', 'Plan Postpago', 6653.28, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (23, 'OPPO Reno12 Pro', 'Plan Prepago', 14669.28, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (24, 'CMF Phone 1', 'Plan Postpago', 5851.68, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (25, 'Sony Xperia 1 VI', 'Plan Prepago', 35139.47, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (26, 'Samsung Galaxy Z Fold6', 'Plan Postpago', 53680.48, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (27, 'Samsung Galaxy Z Flip6', 'Plan Postpago', 32304.48, 10);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (28, 'OnePlus Nord 4', 'Plan Prepago', 14693.32, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (29, 'ZTE Nubia Flip 5G', 'Plan Prepago', 15227.72, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (30, 'Google Pixel 9 Pro XL', 'Plan Postpago', 32838.88, 5);
INSERT INTO Productos (ID_Producto, Nombre, Tipo, Precio_Base, Descuento) VALUES (31, 'iPhone 16 Pro', 'Plan Postpago', 36045.28, 10)
